### PR TITLE
Daf Yomi- some fixes

### PR DESCRIPTION
**Pull request by gnudles**
renamed hebrew names for gmara according to shas vilna.
fixed errors in cycles 1-7 ... (division instead of modulo)

### CODE REVIEW

**Comment by Scimonster** [comment]
There was a typo in זבחים that you caught in the previous PR but missed this time.

**Comment by gnudles** [comment]
That's true, but it was fixed already and I don't know how... see the whole file...

**Comment by Scimonster** [comment]
Looks like it was fixed nearly a year ago. I wonder how it found itself in your code...

**Comment by gnudles** [comment]
כינים is a terrible typo :P

**Pull request merged**
