### PR TITLE
Update hebcal.js

### PR DESCRIPTION
**Pull request by gnudles**
use modulo instead of division, renamed kinnim in hebrew

### CODE REVIEW

**Comment by Scimonster** [comment]
Thanks for your pull request. Sorry i haven't gotten to it yet, i hope to be able to review over the next couple days. Thanks for understanding.

**Comment by Scimonster** [comment]
The files in client are compiled and not meant to be edited directly. Sorry for the confusion. Please make your changes to the relevant files in the project root directory (dafyomi.js), then (if you're on Linux), run `bash setup`. I plan to make a better system for this (#36). If it's too hard to figure out, just make the edits to dafyomi and leave the rest to me.

**Comment by Scimonster** [comment]
Also, please explain why you're changing division to modulo. What bug does it fix?

**Comment by gnudles** [comment]
I get some errors when I try to run setup...
setup: line 19: exorcist: command not found
setup: line 19: browserify: command not found
setup: line 20: node: command not found
setup: line 22: node: command not found
mv: cannot stat 'client.js.map': No such file or directory
setup: line 24: uglifyjs: command not found
Starting hebcal.noloc.js
setup: line 26: browserify: command not found
setup: line 26: exorcist: command not found
setup: line 27: node: command not found
setup: line 29: node: command not found
...
anyway
I changed this:
if (cday >= nsday) { // "new" cycle
		cno = 8 + ( (cday - nsday) / 2711 ); <---- division
		dno = (cday - nsday) % 2711; <---- modulo
	} else { // old cycle
		cno = 1 + ( (cday - osday) / 2702 ); <---- division
		dno = (cday - osday) / 2702; <---- division  XXX WHY?? it should be the day in the cycle, not cycle number... like in the "if"
	}
to be this:
if (cday >= nsday) { // "new" cycle
		cno = 8 + ( (cday - nsday) / 2711 ); <---- division
		dno = (cday - nsday) % 2711; <---- modulo
	} else { // old cycle
		cno = 1 + ( (cday - osday) / 2702 ); <---- division
		dno = (cday - osday) % 2702; <---- modulo
	}

**Comment by Scimonster** [comment]
Okay, maybe make these changes in a different branch and resubmit the PR. I can merge and then recompile.

**Pull request closed without merging**
