### PR TITLE
Fix bug of latitude longitude mismatch

### PR DESCRIPTION
**Pull request by haimkastner**
The first value in 'lat' array (when using setCity method) are the
latitude and not the longitude

### CODE REVIEW

**Comment by Scimonster** [comment]
Thanks for this! I'm bad at this coordinate stuff. (And maintaining, apparently.)

**Comment by avrAhituv** [comment]
Thanks!!
i want to check if this fix my bug,
update this in npm package?

**Comment by Scimonster** [comment]
@avrAhituv Working on a release right now

**Comment by avrAhituv** [comment]
Thank you very much!!
I really appreciate your work.

**Comment by Scimonster** [comment]
v2.3.0 is live on NPM

**Comment by haimkastner** [comment]
Thanks for the npm update and project maintaining.
And it really sounds that this is the bug #51 , because in israel the latitude and longitude are very close.
So if we switch latitude (~32 deg) and longitude (~35 deg) in jerusalem, should be a difference of about 15 minutes.

**Pull request merged**
